server:
  host: "127.0.0.1"
  port: 3000

mysql:
  dbuser:     "root"
  dbpassword: "password"
  dbname:     "mySql"
  dbhost:     "127.0.0.1"
  dbport:     3306

redis:
  host: "127.0.0.3"
  port: 3000
  password: ""
  db: 0